# Generated by Django 3.0.7 on 2020-06-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
