# Generated by Django 3.0.7 on 2020-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200614_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='story',
            old_name='content',
            new_name='content_text',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='author',
            new_name='name',
        ),
    ]
