# Generated by Django 3.0.7 on 2020-06-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200614_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
