# Generated by Django 3.0.7 on 2020-06-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='issue',
            new_name='issue_to_write_about',
        ),
    ]
