# Generated by Django 3.0.7 on 2020-06-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200614_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category_to_write_about',
            field=models.CharField(choices=[('EXP', 'Experiences'), ('REF', 'Reflections'), ('PRO', 'Protests and Demonstrations Info'), ('OTH', 'Other')], default='EXP', max_length=3),
        ),
    ]
