# Generated by Django 3.0.7 on 2020-06-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20200615_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
    ]
