# Generated by Django 3.0.7 on 2020-06-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20200616_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_text',
            field=models.TextField(verbose_name='your Text'),
        ),
    ]
