# Generated by Django 3.0.7 on 2020-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_auto_20200616_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='post Anonymously'),
            preserve_default=False,
        ),
    ]
