# Generated by Django 3.0.7 on 2020-06-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_category_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category_to_write_about',
        ),
        migrations.RemoveField(
            model_name='story',
            name='issue_to_write_about',
        ),
    ]
