# Generated by Django 3.0.7 on 2020-06-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20200619_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='issues',
        ),
    ]
