# Generated by Django 3.0.7 on 2020-06-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0023_remove_category_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category_to_write_about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.Category'),
        ),
        migrations.AddField(
            model_name='story',
            name='issue_to_write_about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.Issue'),
        ),
    ]
