# Generated by Django 3.0.7 on 2020-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_auto_20200619_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='issues',
            field=models.ManyToManyField(to='stories.Issue'),
        ),
    ]
