# Generated by Django 3.0.7 on 2020-06-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_category_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='issues',
        ),
    ]
