# Generated by Django 3.0.7 on 2020-06-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0026_remove_category_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='story_imgs', verbose_name='Optional Picture'),
        ),
    ]
