# Generated by Django 3.0.7 on 2020-06-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_story_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='picture',
        ),
    ]
