# Generated by Django 3.0.7 on 2020-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0029_story_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='picture_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
