# Generated by Django 3.0.7 on 2020-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0030_auto_20200620_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='picture_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Optional Caption for Picture'),
        ),
    ]
