# Generated by Django 3.0.7 on 2020-06-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0032_story_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags (eg., recovery, detroitprotest ...) (separate with commas)'),
        ),
    ]
