# Generated by Django 3.0.7 on 2020-06-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0034_auto_20200622_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='issue_to_write_about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.Issue', verbose_name='Topic to write about'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags (eg., recovery, nurse, detroitprotest, CollegeStudent... ) (separate with commas)'),
        ),
    ]
