# Generated by Django 3.0.7 on 2020-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0036_auto_20200622_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='categories',
            field=models.ManyToManyField(to='stories.Category'),
        ),
    ]
