# Generated by Django 3.0.7 on 2020-06-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0037_issue_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='story',
            name='anonymous',
        ),
    ]
