# Generated by Django 3.0.7 on 2020-07-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0038_auto_20200628_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category_to_write_about',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.Category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='issue_to_write_about',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.Issue', verbose_name='Topic to write about'),
        ),
    ]
