# Generated by Django 3.0.7 on 2020-06-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200626_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
