# Generated by Django 3.0.7 on 2020-06-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='usern',
        ),
    ]
