# Generated by Django 3.0.7 on 2020-06-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200614_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usern',
            new_name='user',
        ),
    ]
