# Generated by Django 3.0.7 on 2020-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200614_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='DEFAULT_JOB', max_length=50),
            preserve_default=False,
        ),
    ]
