# Generated by Django 3.0.7 on 2020-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_img.jpg', upload_to='profile_imgs'),
        ),
    ]
