# Generated by Django 3.0.7 on 2020-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200617_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_img', upload_to='profile_imgs', verbose_name='Profile Picture'),
        ),
    ]
