# Generated by Django 3.0.7 on 2020-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_choice_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice_view',
            field=models.CharField(choices=[('ONE', 'View one story in each row (stories stacked on each other)'), ('TWO', 'View two stories in same row (two stories inline next to each other)')], default='TWO', max_length=3, verbose_name='Choose how you want to see stories of others laid out'),
        ),
    ]
