# Generated by Django 3.0.7 on 2020-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200625_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone_to_use',
            field=models.CharField(default='America/New_York', max_length=30),
            preserve_default=False,
        ),
    ]
