# Generated by Django 3.0.7 on 2020-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200625_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choice_view',
            field=models.CharField(choices=[('ONE', 'View one story in each row (stories stacked on each other)'), ('TWO', 'View two stories in same row (two stories inline next to each other)')], default='TWO', max_length=3, verbose_name='Choose how you want to see stories of others laid out (only applies to larger screens such as laptops and tablets)'),
        ),
    ]
