# Generated by Django 3.0.7 on 2020-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200702_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
