# Generated by Django 3.0.7 on 2020-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms',
            field=models.BooleanField(),
        ),
    ]
