# Generated by Django 3.0.7 on 2020-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200702_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
