# Generated by Django 3.0.7 on 2020-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200702_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='s3://humanity-united-files/default_img.png', upload_to='profile_imgs', verbose_name='Profile Picture'),
        ),
    ]
