# Generated by Django 3.0.7 on 2020-07-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200705_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile_imgs', verbose_name='Profile Picture'),
        ),
    ]
