# Generated by Django 3.0.7 on 2020-07-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20200705_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_imgs.png', upload_to='profile_imgs', verbose_name='Profile Picture'),
        ),
    ]
