# Generated by Django 3.0.7 on 2020-07-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20200705_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_imgs/default_img.png', upload_to='profile_imgs', verbose_name='Profile Picture'),
        ),
    ]
