# Generated by Django 3.0.7 on 2020-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Useful Resources for Topic in Question'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='story_imgs', verbose_name='Picture'),
        ),
    ]
