# Generated by Django 3.0.7 on 2020-06-20 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0004_auto_20200620_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='topic',
        ),
        migrations.AddField(
            model_name='photo',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artworks.Topic'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='default_img.png', upload_to='story_imgs', verbose_name='Picture'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(verbose_name='post Anonymously')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('link_to_resource', models.CharField(max_length=200, verbose_name='Helpful Resource in the form of a link')),
                ('title', models.CharField(max_length=70, verbose_name='Title of Link/Resource')),
                ('description', models.TextField(blank=True, verbose_name='Optional Description of Link/Resource')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artworks.Type')),
                ('issue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artworks.Topic')),
            ],
        ),
    ]
