# Generated by Django 3.0.7 on 2020-06-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20200620_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='issue',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='category',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='issue',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='type',
        ),
    ]
