# Generated by Django 3.0.7 on 2020-06-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20200620_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_to_resource',
            field=models.CharField(max_length=200, verbose_name='Link/URL to Resource'),
        ),
    ]
