# Generated by Django 3.0.7 on 2020-06-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20200622_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags (eg., recovery, nurse, detroitprotest, CollegeStudent... ) (separate with commas)'),
        ),
    ]
