# Generated by Django 3.0.7 on 2020-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_photo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='story_imgs', verbose_name='Picture'),
        ),
    ]
