# Generated by Django 3.0.7 on 2020-06-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20200622_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags (eg., mentalhealth, donate, protestinfo... ) (separate with commas)'),
        ),
    ]
