# Generated by Django 3.0.7 on 2020-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20200623_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='media_type',
            field=models.CharField(default='picture', max_length=10),
            preserve_default=False,
        ),
    ]
