# Generated by Django 3.0.7 on 2020-06-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_photo_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(blank='True', upload_to='individual_imgs', verbose_name='Picture...'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='video',
            field=models.FileField(blank='True', upload_to='individual_vids', verbose_name='...or Video'),
        ),
    ]
