# Generated by Django 3.0.7 on 2020-06-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_commentlink_commentphoto_replylink_replyphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlink',
            old_name='story',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='commentphoto',
            old_name='story',
            new_name='photo',
        ),
    ]
