# Generated by Django 3.0.7 on 2020-06-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_auto_20200624_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artworks.Type', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture_caption',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Optional Caption for Image/Video'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artworks.Type', verbose_name='Category'),
        ),
    ]
