# Generated by Django 3.0.7 on 2020-06-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0023_auto_20200627_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlink',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='commentphoto',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='link',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='replylink',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='replyphoto',
            name='anonymous',
        ),
    ]
